export const CREATE_CARD = 'CREATE_CARD';
export const DELETE_CARD = 'DELETE_CARD';

export const CREATE_LIST = 'CREATE_LIST';
export const DELETE_LIST = 'DELETE_LIST';

export const DRAG_HAPPENED_CARD = 'DRAG_HAPPENED_CARD';
export const DRAG_HAPPENED_LIST = 'DRAG_HAPPENED_LIST';